/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;
import model.Usuario;

/**
 *
 * @author Paulo
 */
public class JFPrincipal extends javax.swing.JFrame {
    private Usuario obj;
    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        initComponents();
        obj = new Usuario();
    }
    
    public JFPrincipal(Usuario obj) {
        this();
        this.obj = obj;
        jlLoginUsuario.setText("Você está logado como: " + obj.getNome());
        if (obj.getTipo() == 1) {
            jbUsuario.setEnabled(true);
            jbMedico.setEnabled(false);
            jbPaciente.setEnabled(false);
            jbConsulta.setEnabled(false);
        }
        else {
            jbUsuario.setEnabled(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbMedico = new javax.swing.JButton();
        jbPaciente = new javax.swing.JButton();
        jbConsulta = new javax.swing.JButton();
        jdpPrincipal = new javax.swing.JDesktopPane();
        jlLoginUsuario = new javax.swing.JLabel();
        jlData = new javax.swing.JLabel();
        jlHora = new javax.swing.JLabel();
        jbUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jbMedico.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/medico.png"))); // NOI18N
        jbMedico.setText("Médico");
        jbMedico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbMedico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMedicoActionPerformed(evt);
            }
        });

        jbPaciente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/paciente.png"))); // NOI18N
        jbPaciente.setText("Paciente");
        jbPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbPaciente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPacienteActionPerformed(evt);
            }
        });

        jbConsulta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consultaMedica.png"))); // NOI18N
        jbConsulta.setText("Consulta");
        jbConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbConsulta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jlLoginUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlLoginUsuario.setText("Você está logado como:");

        jlData.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlData.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlHora.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlHora.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarioSistema.png"))); // NOI18N
        jbUsuario.setText("Usuario");
        jbUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdpPrincipal)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlLoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                        .addComponent(jlData, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlHora, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlLoginUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdpPrincipal)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 110, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMedicoActionPerformed
        JIFMedico janela = new JIFMedico();
        jdpPrincipal.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jbMedicoActionPerformed

    private void jbPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPacienteActionPerformed
        JIFPaciente janela = new JIFPaciente();
        jdpPrincipal.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jbPacienteActionPerformed

    private void jbConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultaActionPerformed
        JIFConsulta janela = new JIFConsulta();
        jdpPrincipal.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jbConsultaActionPerformed

    private void jbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUsuarioActionPerformed
        JIFUsuario janela = new JIFUsuario();
        jdpPrincipal.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jbUsuarioActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        jlData.setText(formatador.format(data));
        
        Timer hora = new Timer(1000, new hora());
        hora.start();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbConsulta;
    private javax.swing.JButton jbMedico;
    private javax.swing.JButton jbPaciente;
    private javax.swing.JButton jbUsuario;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JLabel jlData;
    private javax.swing.JLabel jlHora;
    private javax.swing.JLabel jlLoginUsuario;
    // End of variables declaration//GEN-END:variables
    
    class hora implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            Calendar now = Calendar.getInstance();
            jlHora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }
}
