/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.UsuarioData;
import extras.TratarFormularios;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Usuario;

/**
 *
 * @author Paulo
 */
public class JIFUsuario extends javax.swing.JInternalFrame {
    private Usuario obj;
    private UsuarioData DAO;
    private int acao = 0;
    private ArrayList<Usuario> listaDeUsuarios;
    /**
     * Creates new form JIFUsuario
     */
    public JIFUsuario() {
        try {
            initComponents();
            obj = new Usuario();
            DAO = new UsuarioData();
            listaDeUsuarios = new ArrayList<>();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbSalvar = new javax.swing.JButton();
        jlValorId = new javax.swing.JLabel();
        jbCancelar = new javax.swing.JButton();
        jlNome = new javax.swing.JLabel();
        jbEditar = new javax.swing.JButton();
        jlUsuario = new javax.swing.JLabel();
        jbExcluir = new javax.swing.JButton();
        jlSenha = new javax.swing.JLabel();
        jlPesquisar = new javax.swing.JLabel();
        jlTipo = new javax.swing.JLabel();
        jtfPesquisar = new javax.swing.JTextField();
        jtfNome = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtDados = new javax.swing.JTable();
        jtfUsuario = new javax.swing.JTextField();
        jpfSenha = new javax.swing.JPasswordField();
        jcbTipo = new javax.swing.JComboBox<>();
        jbNovo = new javax.swing.JButton();
        jlId = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Usuários");

        jbSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.setEnabled(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jlValorId.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlValorId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlValorId.setText("0");
        jlValorId.setEnabled(false);

        jbCancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.setEnabled(false);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jlNome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNome.setText("Nome");

        jbEditar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbEditar.setText("Editar");
        jbEditar.setEnabled(false);
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jlUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlUsuario.setText("Usuario");

        jbExcluir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jlSenha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSenha.setText("Senha");

        jlPesquisar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlPesquisar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPesquisar.setText("Pesquisar");

        jlTipo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTipo.setText("Tipo");

        jtfPesquisar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtfPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPesquisarKeyReleased(evt);
            }
        });

        jtfNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtfNome.setEnabled(false);

        jtDados.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtDadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtDados);

        jtfUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtfUsuario.setEnabled(false);

        jpfSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jpfSenha.setEnabled(false);

        jcbTipo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Administrador", "Secretário", " " }));
        jcbTipo.setEnabled(false);

        jbNovo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jlId.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlId.setText("Id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jlId, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jlValorId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jlNome, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jlSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jlTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbCancelar)
                        .addGap(6, 6, 6)
                        .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jlPesquisar)
                        .addGap(35, 35, 35)
                        .addComponent(jtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlId)
                    .addComponent(jlValorId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNome, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbEditar)
                    .addComponent(jbExcluir)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbNovo)
                            .addComponent(jbSalvar)
                            .addComponent(jbCancelar))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        jbNovo.setEnabled(false);
        jbSalvar.setEnabled(true);
        jbCancelar.setEnabled(true);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jtfNome.setEnabled(true);
        jtfUsuario.setEnabled(true);
        jpfSenha.setEnabled(true);
        jcbTipo.setEnabled(true);
        jtfPesquisar.setEnabled(false);
        jtDados.setEnabled(false);
        jtfNome.setText("");
        jtfUsuario.setText("");
        jpfSenha.setText("");
        jcbTipo.setSelectedIndex(0);
        jtfPesquisar.setText("");
        acao = 1;
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        jbNovo.setEnabled(true);
        jbSalvar.setEnabled(false);
        jbCancelar.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jtfNome.setEnabled(false);
        jtfUsuario.setEnabled(false);
        jpfSenha.setEnabled(false);
        jcbTipo.setEnabled(false);
        jtfPesquisar.setEnabled(true);
        jtDados.setEnabled(false);
        jtfNome.setText("");
        jtfUsuario.setText("");
        jpfSenha.setText("");
        jcbTipo.setSelectedIndex(0);
        jtfPesquisar.setText("");
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        try {
            if (validarCampos()) {
                if (preencherObjeto()) {
                    if (acao == 1) {
                        if (DAO.incluir(obj)) {
                            JOptionPane.showMessageDialog(this, "Salvo com sucesso!", "Meu sistema", JOptionPane.INFORMATION_MESSAGE);
                            jbCancelarActionPerformed(evt);
                        }
                        else {
                            JOptionPane.showMessageDialog(this, "Não salvou!");
                        }
                    }
                    if (acao == 2) {
                        if (DAO.editar(obj)) {
                            JOptionPane.showMessageDialog(this, "Editado com sucesso!", "Meu sistema", JOptionPane.INFORMATION_MESSAGE);
                            jbCancelarActionPerformed(evt);
                        }
                        else {
                            JOptionPane.showMessageDialog(this, "Não editou!");
                        }
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jtfPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisarKeyReleased
        try {
            DefaultTableModel mp = (DefaultTableModel) jtDados.getModel();
            mp.setNumRows(0); // limpa quantidade de elementos na lista
            if (jtfPesquisar.getText().length() > 0) {
                listaDeUsuarios = DAO.pesquisar(jtfPesquisar.getText()); // retorna a lista responsável por trazer todos os dados.
                for (Usuario u: listaDeUsuarios) {
                    mp.addRow(new String[]{"" + u.getId(), u.getNome(), "" + u.getTipo()});
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage(), "Erro ao pesquisar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtfPesquisarKeyReleased

    private void jtDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtDadosMouseClicked
        try {
            int linhaSelecionada = jtDados.getSelectedRow();
            if (linhaSelecionada > -1) {
                jlValorId.setText("" + listaDeUsuarios.get(linhaSelecionada).getId());
                jtfNome.setText(listaDeUsuarios.get(linhaSelecionada).getNome());
                jtfUsuario.setText(listaDeUsuarios.get(linhaSelecionada).getUsuario());
                jpfSenha.setText(listaDeUsuarios.get(linhaSelecionada).getSenha());
                jcbTipo.setSelectedIndex(listaDeUsuarios.get(linhaSelecionada).getTipo());
                jbEditar.setEnabled(true);
                jbExcluir.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage(), "Erro ao pesquisar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtDadosMouseClicked

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        try {
            TratarFormularios.habilitarCampos(this);
        } catch (Exception ex) {
            Logger.getLogger(JIFUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        jbNovo.setEnabled(false);
        jbSalvar.setEnabled(true);
        jbCancelar.setEnabled(true);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        acao = 2;
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        try {
            if (DAO.excluir(Integer.parseInt(jlValorId.getText()))) {
                JOptionPane.showMessageDialog(this, "Excluído com sucesso");
                TratarFormularios.limparCampos(this);
                jbEditar.setEnabled(false);
                jbCancelar.setEnabled(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage(), "Erro ao pesquisar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox<String> jcbTipo;
    private javax.swing.JLabel jlId;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlPesquisar;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlTipo;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JLabel jlValorId;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTable jtDados;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfPesquisar;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
    
      private boolean validarCampos() {
        
        String msg = "";
        
        if (jtfNome.getText().length() < 3 || jtfNome.getText().length() > 50) {
            msg += "O nome tem que ter pelo menos 3 ou no máximo 50 caracteres.";
        }
        
        if (jtfUsuario.getText().length() < 5 || jtfPesquisar.getText().length() > 20) {
            msg += "\nO usuário tem que ter pelo menos 5 ou no máximo 20 caracteres.";
        }
        
        if (jpfSenha.getText().length() < 5 || jpfSenha.getText().length() > 20) {
            msg += "\nA senha tem que ter pelo menos 5 ou no máximo 20 caracteres.";
        }
        
        if (jcbTipo.getSelectedIndex() == 0) {
            msg += "\nSelecione um tipo.";
        }
        
        if (msg.length() == 0) {
            return true;
        }
        else {
            JOptionPane.showMessageDialog(this, "Corrija os campos: \n" + msg, "Meu sistema", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    private boolean preencherObjeto() {
        
        obj.setId(Integer.parseInt(jlValorId.getText()));
        obj.setNome(jtfNome.getText());
        obj.setUsuario(jtfUsuario.getText());
        obj.setSenha(jpfSenha.getText());
        obj.setTipo(jcbTipo.getSelectedIndex());
        
        return true;
    }
}
